# Generated by Django 4.2.6 on 2023-10-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo_pdf', models.FileField(upload_to='checklists_pdfs/')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='checklists_images/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.categoria')),
            ],
        ),
    ]
